/**
 * Turns the seeded TypeScript records into supabase/seed.sql so the database and the
 * in-repo fallback can't drift apart. Run after editing any city's data file.
 *
 * Usage: node --experimental-strip-types scripts/generate-seed.mjs
 */

import { writeFile } from "node:fs/promises";
import { PUNE } from "../src/lib/data/pune.ts";

const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;
const array = (values) => `ARRAY[${values.map(quote).join(", ")}]::text[]`;

const rows = PUNE.map(
  (r) =>
    `  (${quote(r.id)}, ${quote(r.name)}, ${quote(r.destination)}, ${quote(r.tag)}, ${quote(r.category)}, ` +
    `${quote(r.priceBand)}, ${r.durationMinutes}, ${r.coords ? r.coords.lat : "null"}, ${r.coords ? r.coords.lng : "null"}, ` +
    `${array(r.interests)}, ${quote(r.timeWindow.start)}, ${quote(r.timeWindow.end)}, ${quote(r.vibe)}, ` +
    `${quote(r.description)}, ${quote(JSON.stringify(r.whyItFits))}::jsonb, ${quote(r.evidenceSource)}, ` +
    `${r.verified}, ${r.priority})`,
);

const sql = `-- Generated by scripts/generate-seed.mjs — do not edit by hand.
-- Run in the Supabase SQL editor after schema.sql.

insert into recommendations
  (id, name, destination, tag, category, price_band, duration_minutes, lat, lng, interests, window_start, window_end, vibe, description, why_it_fits, evidence_source, verified, priority)
values
${rows.join(",\n")}
on conflict (id) do update set
  name = excluded.name,
  destination = excluded.destination,
  tag = excluded.tag,
  category = excluded.category,
  price_band = excluded.price_band,
  duration_minutes = excluded.duration_minutes,
  lat = excluded.lat,
  lng = excluded.lng,
  interests = excluded.interests,
  window_start = excluded.window_start,
  window_end = excluded.window_end,
  vibe = excluded.vibe,
  description = excluded.description,
  why_it_fits = excluded.why_it_fits,
  evidence_source = excluded.evidence_source,
  verified = excluded.verified,
  priority = excluded.priority;
`;

await writeFile(new URL("../supabase/seed.sql", import.meta.url), sql, "utf8");
console.log(`wrote supabase/seed.sql (${PUNE.length} rows)`);
